//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop
    {
        public int CropId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public string CropType { get; set; }
        public string CropName { get; set; }
        public string FertilizerType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PHCertificate { get; set; }
        public string CropApproval { get; set; }
        public Nullable<System.DateTime> CropApprovalDate { get; set; }
        public Nullable<int> BasePrice { get; set; }
    
        //parent obj in child class
        public Farmer Farmer { get; set; }
    }
}
