//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmer()
        {
            this.Crops = new HashSet<Crop>();
        }
    
        public int FarmerID { get; set; }
        public string FFullName { get; set; }
        public string FContactNo { get; set; }
        public string FEmailID { get; set; }
        public string FAddress1 { get; set; }
        public string FAddress2 { get; set; }
        public string FCity { get; set; }
        public string FState { get; set; }
        public string FPincode { get; set; }
        public string FLandAddress { get; set; }
        public string FLandArrea { get; set; }
        public string FLandPincode { get; set; }
        public Nullable<int> FAccountNo { get; set; }
        public string FIfsc { get; set; }
        public string FAadhaar { get; set; }
        public string FPan { get; set; }
        public string FCertificate { get; set; }
        public string FPassword { get; set; }
        public string FApprovalStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //child obj in parent class
        public ICollection<Crop> Crops { get; set; }
       
        //parent object in child class
        public User User { get; set; }
    }
}
